// Centralized product data for the entire store
// lib/all-products.ts
// Centralized product data — generated from Excel

// lib/all-products.ts
// Centralized product data for the store – drawn from your Excel sheet.

export const allProducts = {
  "the-ordinary-niacinamide": {
    id: "the-ordinary-niacinamide",
    name: "The Ordinary Niacinamide",
    price: "3,000 AMD",
    image: "https://45gkphzzl3vmvuua.public.blob.vercel-storage.com/the-ordinary-niacinamide-10-zinc-1-serum",
    category: "Serums",
     description:
      "High-strength, water-based serum designed to target blemishes, regulate oil production, and improve overall skin texture. It’s especially popular for oily and acne-prone skin but suitable for all skin types.",
    benefits: [
      "Visibly reduces the look of enlarged pores",
      "Helps regulate excess sebum production",
      "Minimizes redness and uneven skin tone",
      "Improves skin’s smoothness and radiance",
      "Supports the skin’s natural barrier function",
      "Lightweight, non-sticky texture suitable for layering"
    ],
    howToUse: [
      "Apply a few drops to the entire face morning and evening before heavier creams.",
      "Avoid combining with pure Vitamin C (ascorbic acid) in the same routine to prevent irritation.",
      "Follow with moisturizer and sunscreen during the day."
    ],
    ingredients: [
      "Niacinamide",
      "Zinc PCA",
      "Tamarindus Indica Seed Gum",
      "Pentylene Glycol",
    ],
    skinType: "All skin types (can be drying)",
    size: "30 ml",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    eco: false,
  },

  "anua-heartleaf-pore-control-cleansing-oil": {
    id: "anua-heartleaf-pore-control-cleansing-oil",
    name: "Anua - Heartleaf Pore Control Cleansing Oil",
    price: "8,000 AMD",
    image: "https://45gkphzzl3vmvuua.public.blob.vercel-storage.com/Anua%20-%20Heartleaf%20Pore%20Control%20Cleansing%20Oil",
    category: "Cleansers",
    description: "Lightweight oil cleanser with Heartleaf (Houttuynia) to melt makeup, sunscreen and excess sebum while calming skin. Emulsifies clean without residue; ideal as Step 1 of PM double-cleansing.",
    benefits: ["Dissolves makeup, SPF and impurities",
      "Helps clear pores and reduce blackheads",
      "Soothes redness with Heartleaf extract",
      "Balances skin without stripping",],
    howToUse: ["On dry face, massage 2–3 pumps for 30–60 seconds.",
      "Add water to emulsify until it turns milky.",
      "Rinse well and follow with a water-based cleanser (PM).",],
    ingredients: ["Houttuynia Cordata (Heartleaf) Extract",
      "Cetyl Ethylhexanoate",
      "PEG-20 Glyceryl Triisostearate",
      "Olea Europaea (Olive) Fruit Oil",
      "Macadamia Ternifolia Seed Oil",
      "Tocopherol",],
    skinType: "All skin types (especially combination/oily and sensitive)",
    size: "200 ml",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    eco: false,
  },
  "dr-althea-345-relief-cream": {
    id: "dr-althea-345-relief-cream",
    name: "Dr. Althea - 345 Relief Cream",
    price: "8,800 AMD",
    image: "https://45gkphzzl3vmvuua.public.blob.vercel-storage.com/Dr.%20Althea%20-%20345%20Relief%20Cream",
    category: "Moisturizers",
    description: "Soothing, barrier-supporting cream with Centella, Panthenol and Ceramides to calm irritation and lock in long-lasting moisture without heaviness.",
    benefits: [ "Instant comfort for redness and irritation",
      "Strengthens barrier with Ceramides",
      "Hydrates and softens without greasiness",
      "Great under makeup or as night cream",],
     howToUse: [
      "Use as last step of routine AM/PM.",
      "Apply a pea–nickel sized amount to face and neck.",
      "For extra soothing, layer more on dry zones.",
    ],
    ingredients: [
      "Centella Asiatica Extract",
      "Panthenol (Vitamin B5)",
      "Ceramide NP",
      "Squalane",
      "Allantoin",
      "Sodium Hyaluronate",
    ],
    skinType: "All skin types, including sensitive",
    size: "50 ml",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    eco: false,
  },
  "anua-rice-70-glow-milky-toner": {
    id: "anua-rice-70-glow-milky-toner",
    name: "Anua - Rice 70 Glow Milky Toner",
    price: "8,400 AMD",
    image: "https://45gkphzzl3vmvuua.public.blob.vercel-storage.com/anua_rice_toner.webp",
    category: "Toners",
    description:
      "Milky, fragrance-free toner with 70% Rice extract to brighten, smooth texture and replenish moisture for a bouncy, glass-skin glow.",
    benefits: [
      "Boosts radiance and evens tone",
      "Hydrates and softens rough patches",
      "Preps skin for better absorption",
      "Gentle daily use, AM/PM",
    ],
    howToUse: [
      "After cleansing, apply to hands or cotton pad.",
      "Sweep or pat evenly over face and neck.",
      "Follow with essence/serum and moisturizer.",
    ],
    ingredients: [
      "Oryza Sativa (Rice) Extract 70%",
      "Niacinamide",
      "Glycerin",
      "Panthenol",
      "Allantoin",
      "Hyaluronic Acid",
    ],
    skinType: "All skin types (great for dry/dull)",
    size: "250 ml",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    eco: false,
  },
  "vt-reedle-shot-100": {
    id: "vt-reedle-shot-100",
    name: "VT - Reedle Shot 100",
    price: "14,000 AMD",
    image: "https://45gkphzzl3vmvuua.public.blob.vercel-storage.com/vt-reedle-shot-300",
    category: "Treatments",
    description:
      "Micro-spicule (micro-needle) treatment ampoule to refine texture and boost elasticity. Mild tingling is normal as spicules help deliver actives deeper.",
    benefits: [
      "Refines uneven texture and pores",
      "Supports collagen and firmness",
      "Enhances absorption of actives",
      "Brighter, smoother-looking skin",
    ],
    howToUse: [
      "PM, after toner: apply a thin layer 1–2× weekly.",
      "Do not rub; press and pat gently.",
      "Avoid layering with strong acids/retinoids the same night.",
      "Use SPF daily while using actives.",
    ],
    ingredients: [
      "Hydrolyzed Sponge (Micro-Spicules)",
      "Gluconolactone (PHA)",
      "Centella Asiatica Extract",
      "Bifida Ferment Lysate",
      "Hyaluronic Acid",
      "Peptides",
    ],
    skinType: "Normal, combination, oily (patch test if sensitive)",
    size: "30 ml",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    eco: false,
  },
  "beauty-of-joseon-relief-sun-rice-probiotics-spf-50": {
    id: "beauty-of-joseon-relief-sun-rice-probiotics-spf-50",
    name: "Beauty of Joseon - Relief Sun: Rice + Probiotics SPF 50",
    price: "6,000 AMD",
    image: "https://45gkphzzl3vmvuua.public.blob.vercel-storage.com/Beauty%20of%20Joseon%20-%20Relief%20Sun%3A%20Rice%20%2B%20Probiotics%20SPF%2050",
    category: "Sunscreens",
    description:
      "Weightless chemical sunscreen with Rice extract and grain ferments for moisture and glow. Broad-spectrum SPF50+ PA++++ with zero white cast and great under makeup.",
    benefits: [
      "High UV protection without white cast",
      "Hydrates and brightens with Rice extract",
      "Silky, non-greasy finish",
      "Layers well under makeup",
    ],
    howToUse: [
      "AM, last step of routine: apply generous amount to face/neck.",
      "Reapply every 2–3 hours when outdoors.",
    ],
    ingredients: [
      "Oryza Sativa (Rice) Extract",
      "Niacinamide",
      "Lactobacillus/Rice Ferment",
      "Diethylamino Hydroxybenzoyl Hexyl Benzoate",
      "Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine",
      "Isoamyl p-Methoxycinnamate",
    ],
    skinType: "All skin types",
    size: "50 ml",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    eco: false,
  },
  "axis-y-dark-spot-correcting-glow-serum": {
    id: "axis-y-dark-spot-correcting-glow-serum",
    name: "AXIS - Y - Dark Spot Correcting Glow Serum",
    price: "8,800 AMD",
    image: "https://45gkphzzl3vmvuua.public.blob.vercel-storage.com/AXIS%20-%20Y%20-%20Dark%20Spot%20Correcting%20Glow%20Serum",
    category: "Serums",
    description:
      "Light gel serum with 5% Niacinamide and Squalane to fade dark spots, brighten tone and hydrate without stickiness. Daily-use friendly for acne-prone skin.",
    benefits: [
      "Targets hyperpigmentation and post-acne marks",
      "Evens tone and boosts glow",
      "Hydrates and supports barrier",
      "Gentle for daily AM/PM use",
    ],
    howToUse: [
      "After toner, apply 1–2 pumps to face/neck.",
      "Pat until absorbed; follow with moisturizer.",
      "Use SPF in daytime.",
    ],
    ingredients: [
      "Niacinamide (5%)",
      "Squalane",
      "Rice Bran Extract",
      "Papaya (Carica) Extract",
      "Centella Asiatica",
      "Allantoin",
    ],
    skinType: "All skin types",
    size: "50 ml",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    eco: false,
  },

  "whipped-vegan-pack-cleanser-mugtree": {
    id: "whipped-vegan-pack-cleanser-mugtree",
    name: "WHIPPED - Vegan Pack Cleanser, Mugtree",
    price: "7,600 AMD",
    image: "https://45gkphzzl3vmvuua.public.blob.vercel-storage.com/WHIPPED%20-%20Vegan%20Pack%20Cleanser%2C%20Mugtree",
    category: "Cleansers",
        description:
      "Creamy vegan cleanser with Mugwort to purify and calm. Doubles as a short ‘pack’ (mask) to decongest and soothe without stripping.",
    benefits: [
      "Gently removes impurities and excess oil",
      "Soothes irritation with Mugwort",
      "Can be used as a 3–5 min wash-off pack",
      "Vegan & cruelty-free",
    ],
    howToUse: [
      "As cleanser: massage onto damp skin, rinse.",
      "As pack: apply thicker layer, leave 3–5 min, rinse.",
      "Suitable AM/PM.",
    ],
    ingredients: [
      "Artemisia (Mugwort) Extract",
      "Glycerin",
      "Kaolin",
      "Camellia Sinensis (Green Tea) Extract",
      "Panthenol",
    ],
    skinType: "All skin types (incl. sensitive)",
    size: "150 ml",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    eco: false,
  },

  "eqqualberry-bakuchiol-plumping-serum": {
    id: "eqqualberry-bakuchiol-plumping-serum",
    name: "EQQUALBERRY - Bakuchiol Plumping Serum",
    price: "10,800 AMD",
    image: "https://45gkphzzl3vmvuua.public.blob.vercel-storage.com/EQQUALBERRY%20-%20Bakuchiol%20Plumping%20Serum",
    category: "Serums",
    description:  "Plant-based retinol alternative with Bakuchiol and peptides to soften fine lines, improve elasticity and deliver a plump, hydrated complexion with low irritation.",
    benefits: [
      "Smooths fine lines and improves firmness",
      "Gentle alternative to retinol",
      "Hydrates with HA and Beta-Glucan",
      "Suitable for daily use",
    ],
    howToUse: [
      "Apply 2–3 drops after toner/essence.",
      "Pat to absorb; follow with moisturizer.",
      "Use SPF in daytime.",
    ],
    ingredients: [
      "Bakuchiol",
      "Peptides",
      "Hyaluronic Acid",
      "Panthenol",
      "Beta-Glucan",
      "Aloe Vera Extract",
    ],
    skinType: "All skin types (incl. sensitive/mature)",
    size: "30 ml",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    eco: false,
  },

  "medicube-zero-pore-pad-2-0": {
    id: "medicube-zero-pore-pad-2-0",
    name: "medicube - Zero Pore Pad 2.0",
    price: "10,000 AMD",
    image: "https://45gkphzzl3vmvuua.public.blob.vercel-storage.com/medicube%20-%20Zero%20Pore%20Pad%202.0",
    category: "Exfoliants",
    description:
      "Dual-textured toner pads with BHA/LHA to sweep away dead skin and dissolve pore buildup. Leaves skin smoother and more refined.",
    benefits: [
      "Clears congestion and smooths texture",
      "Refines the look of pores",
      "Controls excess sebum",
      "Preps skin for better absorption",
    ],
    howToUse: [
      "After cleansing, swipe pad across face (avoid eyes).",
      "Start 2–3× weekly; increase as tolerated.",
      "Follow with serum and moisturizer; wear SPF.",
    ],
    ingredients: [
      "Salicylic Acid (BHA)",
      "Lipo-Hydroxy Acid (LHA)",
      "Tea Tree Leaf Extract",
      "Centella Asiatica Extract",
      "Panthenol",
      "Green Tea Extract",
    ],
    skinType: "Combination, oily, acne-prone",
    size: "70 pads / 130–150 ml",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    eco: false,
  },

  "abib-collagen-gel-mask-sedum-jelly": {
    id: "abib-collagen-gel-mask-sedum-jelly",
    name: "Abib - Collagen Gel Mask - Sedum Jelly",
    price: "2,000 AMD",
    image: "https://45gkphzzl3vmvuua.public.blob.vercel-storage.com/Abib%20-%20Collagen%20Gel%20Mask%20-%20Sedum%20Jelly%20with%20hands",
    category: "Masks",
     description:
      "Cooling hydrogel sheet mask infused with Hydrolyzed Collagen and Sedum to deeply hydrate, firm and revive tired skin with a dewy glow.",
    benefits: [
      "Intense hydration and plumping",
      "Firms and revitalizes dull skin",
      "Hydrogel ensures close adherence",
      "Instant glow in 20 minutes",
    ],
    howToUse: [
      "After toner, apply mask to face.",
      "Leave 15–20 minutes, remove.",
      "Pat in remaining essence; no rinse.",
    ],
    ingredients: [
      "Hydrolyzed Collagen",
      "Sedum Sarmentosum Extract",
      "Sodium Hyaluronate",
      "Glycerin",
      "Panthenol",
    ],
    skinType: "All skin types (ideal for dry/mature)",
    size: "1 sheet (25–30 ml essence)",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    eco: false,
  },

  "purito-seoul-mighty-bamboo-panthenol-cream": {
    id: "purito-seoul-mighty-bamboo-panthenol-cream",
    name: "Purito SEOUL - Mighty Bamboo Panthenol Cream",
    price: "8,000 AMD",
    image: "https://45gkphzzl3vmvuua.public.blob.vercel-storage.com/Purito%20SEOUL%20-%20Mighty%20Bamboo%20Panthenol%20Cream",
    category: "Moisturizers",
    description:
      "Barrier-repair cream with Bamboo water and 5% Panthenol to soothe, strengthen and cushion skin with lasting hydration.",
    benefits: [
      "Reinforces barrier and reduces TEWL",
      "Soothes redness and sensitivity",
      "Comfortable, quick-absorbing texture",
      "Nourishing but not greasy",
    ],
    howToUse: [
      "Apply as last step AM/PM.",
      "Reapply on dry areas as needed.",
    ],
    ingredients: [
      "Bambusa (Bamboo) Water",
      "Panthenol (5%)",
      "Ceramide NP",
      "Squalane",
      "Allantoin",
      "Niacinamide",
    ],
    skinType: "Dry, sensitive, normal",
    size: "60–80 ml",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    eco: false,
  },

  "celimax-noni-ampoule-calming-radiance-serum": {
    id: "celimax-noni-ampoule-calming-radiance-serum",
    name: "celimax - Noni Ampoule Calming + Radiance Serum",
    price: "10,000 AMD",
    image: "https://45gkphzzl3vmvuua.public.blob.vercel-storage.com/celimax%20-%20Noni%20Ampoule%20Calming%20%2B%20Radiance%20Serum",
    category: "Serums",
    description:
      "Antioxidant-rich Noni fruit ampoule to calm redness, fortify the skin and boost a healthy glow with lightweight hydration.",
    benefits: [
      "Calms and reduces visible redness",
      "Antioxidant support against stressors",
      "Hydrates and brightens",
      "Skin feels bouncy and resilient",
    ],
    howToUse: [
      "After toner, apply 2–3 drops and pat in.",
      "Use AM/PM; follow with moisturizer.",
    ],
    ingredients: [
      "Morinda Citrifolia (Noni) Extract",
      "Niacinamide",
      "Hyaluronic Acid",
      "Centella Asiatica",
      "Panthenol",
      "Adenosine",
    ],
    skinType: "All skin types (great for stressed/dull)",
    size: "30 ml",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    eco: false,
  },

  "medicube-deep-vita-c-capsule-cream": {
    id: "medicube-deep-vita-c-capsule-cream",
    name: "medicube - Deep Vita C Capsule Cream",
    price: "12,800 AMD",
    image: "https://45gkphzzl3vmvuua.public.blob.vercel-storage.com/medicube%20-%20Deep%20Vita%20C%20Capsule%20Cream",
    category: "Moisturizers",
     description:
      "Brightening cream with Vitamin C micro-capsules that burst upon application to help fade dark spots and even tone while providing antioxidant moisture.",
    benefits: [
      "Visibly brightens and evens complexion",
      "Targets dark spots and dullness",
      "Antioxidant protection (Vit C + E)",
      "Moisturizing yet light feel",
    ],
    howToUse: [
      "After serum, apply to face and neck.",
      "Press gently to burst capsules and spread.",
      "Use SPF during daytime.",
    ],
    ingredients: [
      "Ascorbic Acid (Vitamin C) Capsules",
      "Tocopherol (Vitamin E)",
      "Niacinamide",
      "Panthenol",
      "Hyaluronic Acid",
      "Centella Asiatica",
    ],
    skinType: "All skin types (especially dull/uneven)",
    size: "50 ml",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    eco: false,
  },

  "im-from-mugwort-essence": {
    id: "im-from-mugwort-essence",
    name: "I’m from - Mugwort Essence",
    price: "9,200 AMD",
    image: "https://45gkphzzl3vmvuua.public.blob.vercel-storage.com/I%E2%80%99m%20from%20-%20Mugwort%20Essence",
    category: "Essences",
    description:
      "Single-ingredient essence made with 100% Mugwort (Artemisia) extract from Ganghwa, Korea. Calms inflammation and replenishes hydration for clearer, comfortable skin.",
    benefits: [
      "Reduces redness and irritation",
      "Balances oil and soothes acne-prone skin",
      "Hydrates and supports barrier",
      "Minimalist, fragrance-free formula",
    ],
    howToUse: [
      "After cleansing/toner, apply a generous amount.",
      "Pat in until absorbed; layer if needed.",
    ],
    ingredients: ["100% Artemisia Princeps (Mugwort) Extract"],
    skinType: "All skin types; excellent for sensitive/acne-prone",
    size: "150–160 ml (varies by market)",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    eco: false,
  },

  "dr-althea-vitamin-c-boosting-serum": {
    id: "dr-althea-vitamin-c-boosting-serum",
    name: "Dr. Althea - Vitamin C Boosting Serum",
    price: "14,000 AMD",
    image: "https://45gkphzzl3vmvuua.public.blob.vercel-storage.com/Dr.%20Althea%20-%20Vitamin%20C%20Boosting%20Serum",
    category: "Serums",
     description:
      "Potent brightening serum with stabilized Vitamin C derivative plus Niacinamide and Hyaluronic Acid to improve radiance, fade spots and provide antioxidant care.",
    benefits: [
      "Visibly brightens and evens tone",
      "Helps fade pigmentation and spots",
      "Antioxidant protection against stressors",
      "Hydrating, layer-friendly texture",
    ],
    howToUse: [
      "After toner, apply a few drops to face/neck.",
      "Pat until absorbed; follow with moisturizer.",
      "Use SPF in daytime.",
    ],
    ingredients: [
      "3-O-Ethyl Ascorbic Acid (Vit C derivative)",
      "Niacinamide",
      "Hyaluronic Acid",
      "Centella Asiatica Extract",
      "Adenosine",
    ],
    skinType: "All skin types (patch test if sensitive)",
    size: "30 ml",
    rating: 4.5,
    reviews: 0,
    inStock: true,
    eco: false, 
  },
  
} as const

export type Product = (typeof allProducts)[keyof typeof allProducts]
