-- Insert all products with their categories
INSERT INTO products (
  id, category_id, name_en, description_en, name_ru, description_ru, name_hy, description_hy,
  price, image, benefits_en, benefits_ru, benefits_hy, how_to_use_en, how_to_use_ru, how_to_use_hy,
  ingredients, skin_type_en, skin_type_ru, skin_type_hy, size, rating, reviews, in_stock, eco
) VALUES
(
  'the-ordinary-niacinamide',
  'serums',
  'The Ordinary Niacinamide',
  'High-strength, water-based serum designed to target blemishes, regulate oil production, and improve overall skin texture. It''s especially popular for oily and acne-prone skin but suitable for all skin types.',
  'The Ordinary Ниацинамид',
  'Высококонцентрированная водная сыворотка, разработанная для борьбы с несовершенствами, регулирования выработки кожного сала и улучшения общей текстуры кожи. Особенно популярна для жирной и склонной к акне кожи, но подходит для всех типов кожи.',
  'The Ordinary Նիացինամիդ',
  'Բարձր ամրությամբ ջրահիմն շիճուկ, նախագծված պզուկների դեմ պայքարի, յուղի արտադրության կարգավորման և մաշկի հյուսվածքի բարելավման համար:',
  '3,000 AMD',
  'https://45gkphzzl3vmvuua.public.blob.vercel-storage.com/the-ordinary-niacinamide-10-zinc-1-serum',
  ARRAY['Visibly reduces the look of enlarged pores', 'Helps regulate excess sebum production', 'Minimizes redness and uneven skin tone', 'Improves skin''s smoothness and radiance', 'Supports the skin''s natural barrier function', 'Lightweight, non-sticky texture suitable for layering'],
  ARRAY['Визуально уменьшает расширенные поры', 'Помогает регулировать избыточную выработку кожного сала', 'Минимизирует покраснение и неровный тон кожи', 'Улучшает гладкость и сияние кожи', 'Поддерживает естественную барьерную функцию кожи', 'Легкая, нелипкая текстура, подходящая для наслоения'],
  ARRAY['Տեսողականորեն նվազեցնում է ընդլայնված ծակոտիների տեսքը', 'Օգնում է կարգավորել ավելորդ մաշկային յուղի արտադրությունը', 'Նվազեցնում է կարմրությունը և անհավասար մաշկի տոնը', 'Բարելավում է մաշկի հարթությունը և փայլը', 'Աջակցում է մաշկի բնական պաշտպանիչ գործառույթը', 'Թեթև, ոչ կպչուն հյուսվածք, հարմար շերտավորման համար'],
  ARRAY['Apply a few drops to the entire face morning and evening before heavier creams.', 'Avoid combining with pure Vitamin C (ascorbic acid) in the same routine to prevent irritation.', 'Follow with moisturizer and sunscreen during the day.'],
  ARRAY['Наносите несколько капель на все лицо утром и вечером перед более плотными кремами.', 'Избегайте сочетания с чистым витамином С (аскорбиновой кислотой) в одной процедуре, чтобы предотвратить раздражение.', 'Затем нанесите увлажняющий крем и солнцезащитный крем в течение дня.'],
  ARRAY['Քսեք մի քանի կաթիլ ամբողջ դեմքին առավոտ և երեկո ավելի ծանր քսուքներից առաջ:', 'Խուսափեք զուտ վիտամին C-ի (ասկորբինաթթու) հետ համատեղելուց նույն ընթացակարգում՝ գրգռումից խուսափելու համար:', 'Հետևեք խոնավեցնող միջոցով և արևապաշտպան քսուքով օրվա ընթացքում:'],
  ARRAY['Niacinamide', 'Zinc PCA', 'Tamarindus Indica Seed Gum', 'Pentylene Glycol'],
  'All skin types (can be drying)',
  'Все типы кожи (может сушить)',
  'Բոլոր մաշկի տեսակները (կարող է չորացնել)',
  '30 ml',
  4.5,
  0,
  true,
  false
),
(
  'anua-heartleaf-pore-control-cleansing-oil',
  'cleansers',
  'Anua - Heartleaf Pore Control Cleansing Oil',
  'Lightweight oil cleanser with Heartleaf (Houttuynia) to melt makeup, sunscreen and excess sebum while calming skin. Emulsifies clean without residue; ideal as Step 1 of PM double-cleansing.',
  'Anua - Очищающее масло Heartleaf для контроля пор',
  'Легкое очищающее масло с экстрактом сердцелистного (Houttuynia) для растворения макияжа, солнцезащитного крема и избытка кожного сала, успокаивая кожу. Эмульгирует чисто без остатка; идеально как Шаг 1 вечернего двойного очищения.',
  'Anua - Heartleaf ծակոտիների վերահսկման մաքրող յուղ',
  'Թեթև մաքրող յուղ Heartleaf-ով (Houttuynia)՝ կոսմետիկա, արևապաշտպան միջոց և ավելորդ յուղ հալեցնելու համար՝ միաժամանակ հանգստացնելով մաշկը:',
  '8,000 AMD',
  'https://45gkphzzl3vmvuua.public.blob.vercel-storage.com/Anua%20-%20Heartleaf%20Pore%20Control%20Cleansing%20Oil',
  ARRAY['Dissolves makeup, SPF and impurities', 'Helps clear pores and reduce blackheads', 'Soothes redness with Heartleaf extract', 'Balances skin without stripping'],
  ARRAY['Растворяет макияж, SPF и загрязнения', 'Помогает очистить поры и уменьшить черные точки', 'Успокаивает покраснение с экстрактом Heartleaf', 'Балансирует кожу без пересушивания'],
  ARRAY['Լուծում է կոսմետիկան, SPF և աղտոտումները', 'Օգնում է մաքրել ծակոտիները և նվազեցնել սև կետերը', 'Հանգստացնում է կարմրությունը Heartleaf էքստրակտով', 'Հավասարակշռում է մաշկը առանց չորացման'],
  ARRAY['On dry face, massage 2–3 pumps for 30–60 seconds.', 'Add water to emulsify until it turns milky.', 'Rinse well and follow with a water-based cleanser (PM).'],
  ARRAY['На сухое лицо нанесите 2-3 помпы и массируйте 30-60 секунд.', 'Добавьте воду для эмульгирования, пока не станет молочным.', 'Тщательно смойте и используйте водный очищающий гель (вечером).'],
  ARRAY['Չոր դեմքին զանգվածեք 2-3 պոմպ 30-60 վայրկյան:', 'Ավելացրեք ջուր՝ էմուլսիայի համար, մինչև կաթնային դառնա:', 'Լավ լվացեք և օգտագործեք ջրային մաքրող միջոց (երեկոյան):'],
  ARRAY['Houttuynia Cordata (Heartleaf) Extract', 'Cetyl Ethylhexanoate', 'PEG-20 Glyceryl Triisostearate', 'Olea Europaea (Olive) Fruit Oil', 'Macadamia Ternifolia Seed Oil', 'Tocopherol'],
  'All skin types (especially combination/oily and sensitive)',
  'Все типы кожи (особенно комбинированная/жирная и чувствительная)',
  'Բոլոր մաշկի տեսակները (հատկապես խառը/յուղոտ և զգայուն)',
  '200 ml',
  4.5,
  0,
  true,
  false
)
-- Add remaining products here (continuing in next part due to length)
ON CONFLICT (id) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name_en = EXCLUDED.name_en,
  description_en = EXCLUDED.description_en,
  name_ru = EXCLUDED.name_ru,
  description_ru = EXCLUDED.description_ru,
  name_hy = EXCLUDED.name_hy,
  description_hy = EXCLUDED.description_hy,
  price = EXCLUDED.price,
  image = EXCLUDED.image,
  benefits_en = EXCLUDED.benefits_en,
  benefits_ru = EXCLUDED.benefits_ru,
  benefits_hy = EXCLUDED.benefits_hy,
  how_to_use_en = EXCLUDED.how_to_use_en,
  how_to_use_ru = EXCLUDED.how_to_use_ru,
  how_to_use_hy = EXCLUDED.how_to_use_hy,
  ingredients = EXCLUDED.ingredients,
  skin_type_en = EXCLUDED.skin_type_en,
  skin_type_ru = EXCLUDED.skin_type_ru,
  skin_type_hy = EXCLUDED.skin_type_hy,
  size = EXCLUDED.size,
  rating = EXCLUDED.rating,
  in_stock = EXCLUDED.in_stock,
  eco = EXCLUDED.eco;
